name = "LargeStatisticalSimulationStudy"
uuid = "22b29e9b-97e2-48d9-baab-6c2040e9b618"
authors = ["Andrew Simpson"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
